### ISSUE TITLE
mirrorace error

### ISSUE THREAD

**Issue by xcoders-hub** [Akouji/YamiDrive-Google-Drive-Sharer#2]
It Shows only file id when try to upload on mirrorace.

**Comment by Akouji** [comment]
Sorry for being late, I just tried on YamiDrive web and it didn't get an error.

If when you create a mirror on YamiDrive and a 403 error appears, it's because the Mirrorace API can only upload (maybe) 10-15 files per day. So it might have been the limit when you tried.

Maybe you mean an error in the mirrorace.php file in this repository, because what I am sharing is not a full script, it's just a backup and there are a few important lines of code that I deleted before I created this repository.

if you want to learn more you can see the documentation at [https://mirrorace.com/api](https://mirrorace.com/api)
thank you.
